#!/usr/bin/env bash

# Python packages necessary for the flight program to run
PYTHON_PACKAGES=(
    adafruit-blinka
    adafruit-circuitpython-bno055
    adafruit-circuitpython-mpl3115a2
    adafruit-circuitpython-servokit
    numpy
    )

# Install all packages
for package in $PYTHON_PACKAGES; do
    python3 -m pip install --user $package
done
