#!/usr/bin/env bash
# Clean log and/or data files, based on arguments
# Run cleantxt like so:
#   ./cleantxt ALL

if [ "$1" == "ALL" ]; then
	find -type f -name "*DATA*" -delete
	find -type f -name "*LOG*" -delete
else
	find -type f -name "*${1}*" -delete
fi

